import os
import json

def read_file(filepath):
    if not os.path.exists(filepath):
        return ""
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def create_kaggle_notebook(output_filename, app_filename):
    notebook = {
        "cells": [],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }

    def add_markdown(text):
        notebook["cells"].append({
            "cell_type": "markdown",
            "metadata": {},
            "source": text.splitlines(True)
        })

    def add_code(code):
        notebook["cells"].append({
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": code.splitlines(True)
        })

    # Header Markdown
    add_markdown("# 👁️ NAZARA: Edge-Native Assistive Co-Pilot for the Visually Impaired\n"
                 "**Powered by Google Gemma 4 (4-Bit Quantized) on T4 GPU**\n\n"
                 "This notebook packages the complete NAZARA pipeline into a single runnable instance. "
                 "Run the cells sequentially. The final cell will generate a public Gradio link you can open on your smartphone.")

    # Requirements (First cell ensures packages load before subsequent imports)
    add_markdown("### 1. Environment Setup\n"
                 "Install all strict dependencies (Transformers, BitsAndBytes, Edge-TTS, Gradio).")
    add_code("!pip install -r requirements.txt\nimport time\ntime.sleep(2)")

    # Config
    add_markdown("### 2. Configuration (`config.py`)")
    add_code(read_file("config.py"))

    # Prompts
    add_markdown("### 3. Core Prompts (`src/prompts.py`)")
    add_code(read_file("src/prompts.py"))

    # Tools
    add_markdown("### 4. Agentic Tool Dispatcher (`src/tools.py`)")
    add_code(read_file("src/tools.py"))
    
    # Audio Service
    add_markdown("### 5. Asynchronous TTS (`src/audio_service.py`)")
    add_code(read_file("src/audio_service.py"))

    # Engine
    add_markdown("### 6. Multimodal Engine (`src/model_engine.py`)")
    add_code(read_file("src/model_engine.py"))

    # App
    add_markdown("### 7. Launch Gradio UI\n"
                 "**Instructions:** Click the public link generated by this cell. Ensure you allow Camera/Microphone permissions on your device.")
    
    app_code = read_file(app_filename)
    # Replace share=False with share=True for Kaggle public access
    app_code = app_code.replace("share=False", "share=True")
    add_code(app_code)

    with open(output_filename, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2)

    print(f"Successfully exported '{output_filename}'.")

if __name__ == "__main__":
    create_kaggle_notebook("nazara_gemma4_demo.ipynb", "app.py")
    create_kaggle_notebook("nazara_kaggle_submission.ipynb", "src/app.py")
